import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profilePic from "../../public/images/profile/ankana.png"
import AnimatedText, { AnimatedTextWord } from '@/components/AnimatedText'
import {motion} from 'framer-motion'
import {LinkedinIcon,GithubIcon,InstagramIcon,FacebookIcon,LinkArrow} from '../components/Icons'
import { fromJSON } from 'postcss'
import Link from 'next/link'
import HireMe from '@/components/HireMe'
import Preloader from "@/components/Preloader";
import { useState,useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

const animation = {
  initial:{
      opacity:0,
      y:10,
      
  },
  animate:{
      opacity:1,
      y:-10,
      
      transition:{
          delay:3,
        
      }
  }
}

const animation2 = {
  initial:{
      opacity:0,
      y:10,
      
  },
  animate:{
      opacity:1,
      y:-10,
      
      transition:{
          delay:9,
        
      }
  }
}

const animation3 = {
  initial:{
      opacity:0,
      y:10,
      
  },
  animate:{
      opacity:1,
      y:-10,
      
      transition:{
          delay:10,
        
      }
  }
}


export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Simulate loading time
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 3000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <>
    {isLoading && <Preloader setIsLoading={setIsLoading} />}   
      <Head>
        <title>Ankana Chatterjee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <motion.Layout className='flex justify-center items-center text-dark dark:text-light w-full  xs:px-12 xs:py-10 sm:px-16 sm:py-12 md:px-16 md:py-5 lg:px-8 lg:py-14 xl:px-16 xl:py-4 2xl:px-32 2xl:py-8'>
          <div className='flex xs:flex-col sm:flex-col  md:flex-col lg:flex-row xl:flex-row  items-center justify-between w-full'>
            <motion.div className='w-full xs:px-8 sm:px-16 md:px-32 md:w-full md:ml-0 lg:w-1/3 lg:ml-10 xl:w-1/3 xl:ml-10 2xl:w-1/1.5 ' variants={animation} initial="initial" animate="animate">
              <Image src={profilePic} alt="Ankana" className='w-full relative' />
            </motion.div>
            <div className='w-full xs:ml-0 sm:ml-0  md:w-full md:mr-0 lg:w-1/2 lg:mr-10 xl:w-1/2 xl:mr-10 2xl:ml-10 flex flex-col md:text-center '>
              <AnimatedText className='dark:text-light md:text-center' text="Ankana Chatterjee"></AnimatedText>
              <AnimatedTextWord className='2xl:text-lg xl:text-md lg:text-md md:text-md sm:text-sm xs:text-xs' text="As a skilled full stack developer, I am dedicated to turning ideas into innovative web applications. Explore my website showcasing my expertise in the field of Computer Science."></AnimatedTextWord>
              <motion.div className='flex flex-wrap mt-5 md:justify-center ' variants={animation2} initial="initial" animate="animate">
                      <motion.a href="https://www.linkedin.com/in/ankana-chatterjee-4102ab1bb/" target={"_blank"} whileHover={{y:-2}} whileTap={{scale:0.9}} className='w-6 mr-3'><LinkedinIcon/></motion.a>
                      <motion.a href="https://github.com/ANKANACHATTERJEE" target={"_blank"} whileHover={{y:-2}} whileTap={{scale:0.9}} className='w-6 mx-3'><GithubIcon/></motion.a>
                      <motion.a href="https://www.instagram.com/_._ankana_._/" target={"_blank"} whileHover={{y:-2}} whileTap={{scale:0.9}} className='w-6 mx-3'><InstagramIcon/></motion.a>
                      <motion.a href="https://www.facebook.com/profile.php?id=100094751014816" target={"_blank"} whileHover={{y:-2}} whileTap={{scale:0.9}} className='w-6 ml-3'><FacebookIcon/></motion.a>
              </motion.div>
              <motion.div className='flex items-center md:justify-center md:mt-5 mt-10 ' variants={animation3} initial="initial" animate="animate">
                <Link href="/ANKANA CHATTERJEE_2026_RESUME.pdf" target={"_blank"} className="flex 2xl:text-lg xl:text-md lg:text-md md:text-md sm:text-sm xs:text-xs items-center bg-dark text-light xs:px-1 xs:py-0.5 sm:px-1.5 sm:py-1 md:px-2 md:py-1.5 lg:px-2.5 lg:py-2 xl:px-4 xl:py-2.5 2xl:px-5 2xl:py-2.5 rounded-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark dark:hover:text-light dark:hover:bg-dark dark:hover:border-light" download={true}>Resume<LinkArrow className={"xs:w-3 sm:w-4 md:w-5 lg:w-5 xl:w-6 2xl:w-6 ml-1"}/></Link>
                <Link href="mailto:ankana.chatterjee02@gmail.com" target={"_blank"} className="xs:ml-2 sm:ml-2 md:ml-4 lg:ml-4 xl:ml-4 2xl:ml-4   capitalize text-dark underline dark:text-light 2xl:text-lg xl:text-md lg:text-md md:text-md sm:text-sm xs:text-xs">Contact</Link>
              </motion.div>
            </div>
          </div>
        </motion.Layout>
        
      </main>
    </>
  )
}
